import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { mkdir } from 'node:fs/promises';
import { createServer } from 'vite';
import * as XLSX from 'xlsx';
import { startAbaTestServer } from '../../server/tests/abaHarness.js';
import { asinFirst, asinSecond, asinFixture, mergedFixture } from '../../server/tests/abaAsinFixture.js';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = fileURLToPath(new URL('../', import.meta.url));
const output = fileURLToPath(new URL('../../.tmp/', import.meta.url));
await mkdir(output, { recursive: true });
const backend = await startAbaTestServer();
let vite, browser;
try {
  vite = await createServer({ root, server: { host: '127.0.0.1', port: 0, proxy: { '/api': { target: backend.url, changeOrigin: true } } } });
  await vite.listen();
  browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || 'msedge', headless: true });
  const page = await browser.newPage({ viewport: { width: 1600, height: 1080 }, reducedMotion: 'reduce' });
  page.setDefaultTimeout(12000);
  const errors = [];
  page.on('pageerror', (err) => errors.push(err.message));
  await page.goto(`http://127.0.0.1:${vite.httpServer.address().port}`);
  await page.getByLabel('用户名').fill('aba-test');
  await page.getByLabel('密码', { exact: true }).fill('local-test-password');
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await page.locator('.topnav').getByRole('button', { name: 'ABA 报告', exact: true }).click();
  await page.getByRole('button', { name: 'ASIN 视图', exact: true }).click();
  const view = page.locator('.aba-asin-view');
  const idle = () => view.locator('.aba-results[aria-busy="false"]').waitFor();
  const rows = () => view.locator('.aba-table tbody tr');
  const attach = async (files) => {
    await view.locator('input[type="file"]').setInputFiles(files.map((f) => ({ name: f.name, mimeType: 'text/csv', buffer: Buffer.from(f.text) })));
    await view.locator('.aba-file strong').getByText(files.at(-1).name, { exact: true }).waitFor();
  };
  await idle();
  assert.match(await view.locator('.aba-table-empty').innerText(), /还没有 ASIN 报告/);
  await attach([{ name: 'invalid.csv', text: 'bad' }]);
  assert.match(await view.locator('.aba-file').innerText(), /A1/);
  assert.equal(await view.getByRole('button', { name: '上传并保存' }).isDisabled(), true);
  const empty = { name: 'empty.csv', text: asinFixture({ asin: 'B000000302', rows: [] }) };
  await attach([asinFirst, asinSecond, empty]);
  assert.match(await view.locator('.aba-file').last().innerText(), /空周报/);
  await view.getByRole('button', { name: '上传并保存' }).click();
  await view.getByText(/已保存 4 条/).waitFor();
  await idle();
  assert.equal(await rows().count(), 4);
  assert.equal(await view.locator('.aba-table th').count(), 11);
  const printer = () => rows().filter({ hasText: 'hp deskjet 2820e' });
  assert.match(await printer().innerText(), /25.00%[\s\S]*53.33%[\s\S]*26.67%/);
  await printer().locator('summary').click();
  assert.match(await printer().innerText(), /第 36 周[\s\S]*第 35 周/);
  assert.match(await printer().innerText(), /未关联 SKU/);
  const imported = await page.request.post(new URL('/api/sku/rows', page.url()).href, { data: { rows: [
    { country: 'ES', brand: 'Test CY', model: '305', sku: 'TEST-305-BK', setGroup: 'BK', asin: 'B000000305' },
    { country: 'ES', brand: 'Test CY', model: '305', sku: 'TEST-305-BKC', setGroup: 'BKC', asin: 'B000000305' },
  ] } });
  assert.equal(imported.ok(), true);
  await view.getByLabel('月份', { exact: true }).selectOption('09');
  await idle();
  assert.equal(await rows().count(), 2);
  assert.equal(await view.locator('.aba-weeks input:checked').count(), 1);
  assert.match(await printer().innerText(), /TEST-305-BK[\s\S]*TEST-305-BKC/);
  const skuSelect = view.getByLabel('关联 SKU', { exact: true });
  const skuId = await skuSelect.locator('option').filter({ hasText: 'TEST-305-BKC' }).getAttribute('value');
  await skuSelect.selectOption(skuId);
  await idle();
  assert.equal(await rows().count(), 2);
  assert.equal(await view.locator('.aba-asin-sku').count(), 2);
  assert.match(await view.locator('.aba-asin-sku').first().innerText(), /BKC/);
  await view.getByLabel('月份', { exact: true }).selectOption('');
  await idle();
  await view.getByRole('button', { name: '全选', exact: true }).click();
  await idle();
  await view.getByLabel('多周合并相同搜索词').uncheck();
  await idle();
  assert.equal(await rows().count(), 6);
  await view.getByLabel('多周合并相同搜索词').check();
  await idle();
  await view.getByLabel('搜索查询 / 墨盒型号').fill('305');
  await page.waitForResponse((r) => r.url().includes('/api/aba/asin?') && r.url().includes('q=305'));
  await idle();
  await view.getByLabel('词类型', { exact: true }).selectOption('printer');
  await idle();
  assert.equal(await rows().count(), 2);
  assert.doesNotMatch(await view.locator('.aba-table tbody').innerText(), /deskjet 3050/);
  await view.getByLabel('词类型', { exact: true }).selectOption('cartridge');
  await idle();
  assert.equal(await rows().count(), 1);
  await view.getByRole('button', { name: '清除搜索', exact: true }).click();
  await idle();
  assert.equal(await view.getByLabel('搜索查询 / 墨盒型号').evaluate((e) => e === document.activeElement), true);
  await view.getByLabel('词类型', { exact: true }).selectOption('all');
  await idle();
  await view.getByLabel('ASIN', { exact: true }).selectOption('B000000302');
  await idle();
  assert.match(await view.locator('.aba-table-empty').innerText(), /所选报告没有搜索词数据/);
  await view.getByLabel('ASIN', { exact: true }).selectOption('B000000305');
  await idle();
  await view.getByRole('button', { name: '全选', exact: true }).click();
  await idle();
  await view.locator('th button').filter({ hasText: '品牌占有率' }).click();
  await idle();
  assert.equal(await view.locator('th[aria-sort="descending"]').count(), 1);
  assert.match(await rows().first().innerText(), /hp 4310/);
  await page.screenshot({ path: output + 'aba-asin-desktop.png', fullPage: true });
  await page.getByRole('button', { name: '切换主题', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: output + 'aba-asin-narrow-dark.png', fullPage: true });
  assert.ok(await view.locator('.aba-table-scroll').evaluate((e) => e.scrollWidth > e.clientWidth));
  assert.ok(await view.evaluate((e) => e.getBoundingClientRect().right <= innerWidth + 1));
  await page.setViewportSize({ width: 1600, height: 1080 });
  await page.getByRole('button', { name: '切换主题', exact: true }).click();
  await page.route('**/api/aba/asin?**', (route) => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: '暂不可用，请重试' }) }));
  await view.getByLabel('月份', { exact: true }).selectOption('08');
  await view.getByRole('button', { name: '重新加载' }).waitFor();
  await page.unroute('**/api/aba/asin?**');
  await view.getByRole('button', { name: '重新加载' }).click();
  await idle();
  assert.equal(await rows().count(), 4);
  await attach([asinSecond]);
  await page.route('**/api/aba/asin/import', (route) => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: '保存暂不可用' }) }));
  await view.getByRole('button', { name: '上传并保存' }).click();
  await view.getByRole('alert').waitFor();
  assert.equal(await view.locator('.aba-file').count(), 1);
  await page.unroute('**/api/aba/asin/import');
  await view.getByRole('button', { name: '上传并保存' }).click();
  await view.getByText(/已存在，无需重复保存/).waitFor();
  await idle();
  await page.reload();
  await page.locator('.topnav').getByRole('button', { name: 'ABA 报告', exact: true }).click();
  await page.getByRole('button', { name: 'ASIN 视图', exact: true }).click();
  await idle();
  assert.equal(await rows().count(), 2);
  assert.match(await printer().innerText(), /TEST-305-BKC/);
  assert.deepEqual(errors, []);
  await page.locator('.topnav').getByRole('button', { name: 'SKU 库', exact: true }).click();
  const skuRow = page.locator('.tbl tbody tr').filter({ hasText: 'TEST-305-BKC' })
    .or(page.locator('.tbl tbody tr').filter({ has: page.getByLabel('ASIN TEST-305-BKC', { exact: true }) }));
  await skuRow.getByRole('button', { name: '编辑', exact: true }).click();
  await skuRow.getByLabel('ASIN TEST-305-BKC', { exact: true }).fill('bad');
  await skuRow.getByRole('button', { name: '保存', exact: true }).click();
  await page.getByRole('alert').getByText(/ASIN 须为/).waitFor();
  assert.equal(await skuRow.getByLabel('ASIN TEST-305-BKC', { exact: true }).inputValue(), 'bad');
  await skuRow.getByLabel('ASIN TEST-305-BKC', { exact: true }).fill('B000000302');
  await skuRow.getByRole('button', { name: '保存', exact: true }).click();
  await page.getByRole('status').getByText('已保存', { exact: true }).waitFor();
  await page.locator('.topnav').getByRole('button', { name: 'ABA 报告', exact: true }).click();
  await page.getByRole('button', { name: 'ASIN 视图', exact: true }).click();
  await idle();
  assert.doesNotMatch(await printer().innerText(), /TEST-305-BKC/);
  assert.deepEqual(errors, []);
  const manyRows = [...Array.from({ length: 30 }, (_, i) => [`hp deskjet 2820e pack ${i}`, 100, 1000, 100, 20, 200, 10, 5]), ['generic ink', 20, 100, 10, 2, 40, 5, 1]];
  const combined = mergedFixture([{ name: 'a.csv', text: asinFixture({ rows: manyRows }) }, { name: 'b.csv', text: asinFixture({ rows: manyRows, week: 36, start: '2026-08-30', end: '2026-09-05' }) }]);
  const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(combined.sheets[0].rows), 'B999999999_wrong_week');
  await view.locator('input[type="file"]').setInputFiles({ name: '合并表.xlsx', mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', buffer: XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }) });
  await view.locator('.aba-file').getByText('2 份周报 · 62 条记录', { exact: true }).waitFor();
  await view.getByRole('button', { name: '上传并保存' }).click();
  await view.getByText(/已更新 31 条/).waitFor();
  await idle();
  await view.getByLabel('显示方式', { exact: true }).selectOption('printers');
  await idle();
  assert.equal(await view.locator('.aba-group-row').count(), 2);
  assert.match(await view.locator('.aba-group-row').filter({ hasText: '墨盒 KW 词' }).innerText(), /2/);
  await view.getByRole('button', { name: '展开 B000000305 HP DESKJET2820', exact: true }).click();
  const children = view.getByRole('region', { name: 'B000000305 HP DESKJET2820 下的搜索词', exact: true });
  await children.locator('.aba-table').waitFor();
  assert.equal(await children.locator('tbody tr').count(), 25);
  assert.match(await children.locator('.aba-group-context').innerText(), /30 个搜索词.*ASIN 总点击 600.*ASIN 总购买 300/);
  await children.getByRole('button', { name: '下一页' }).click();
  await children.getByText('2 / 2 页', { exact: true }).waitFor();
  assert.equal(await children.locator('tbody tr').count(), 5);
  await view.locator('.aba-table-heading').scrollIntoViewIfNeeded();
  await page.screenshot({ path: output + 'aba-asin-grouped.png', fullPage: true });
  await view.getByRole('button', { name: '收起 B000000305 HP DESKJET2820', exact: true }).click();
  await page.route('**/api/aba/asin?**group=**', (route) => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: '分类请求失败' }) }));
  await view.getByRole('button', { name: '展开 B000000305 墨盒 KW 词', exact: true }).click();
  await view.getByRole('button', { name: '重试分类明细' }).waitFor();
  await page.unroute('**/api/aba/asin?**group=**');
  await view.getByRole('button', { name: '重试分类明细' }).click();
  await view.locator('.aba-group-details .aba-table').waitFor();
  assert.match(await view.locator('.aba-group-details .aba-table tbody').innerText(), /generic ink/);
  await view.getByLabel('词类型', { exact: true }).selectOption('cartridge');
  await idle();
  assert.equal(await view.locator('.aba-group-row').count(), 1);
  if (process.env.ASIN_MERGED_FILE) {
    await view.locator('input[type="file"]').setInputFiles(process.env.ASIN_MERGED_FILE);
    await view.locator('.aba-file').getByText('8 份周报 · 166 条记录', { exact: true }).waitFor();
    await view.getByRole('button', { name: '上传并保存' }).click();
    await view.getByText(/B08Z73WF68 2026-08-29/).last().waitFor();
    await idle();
    const response = await page.request.get(new URL('/api/aba/asin?marketplace=ES&asin=B0GXB65GFF&weeks=2026-08-29&pageSize=500', page.url()).href);
    const imported = await response.json();
    assert.equal(imported.recordCount, 67);
    assert.equal(imported.items.reduce((s, r) => s + r.asin_purchases, 0), 5);
  }
  assert.deepEqual(errors, []);
  const one = 'B000002001', two = 'B000002002';
  const oneRow = ['hp deskjet 2820e', 100, 1000, 100, 20, 200, 10, 5];
  const twoRow = ['hp deskjet 2820e', 100, 1000, 100, 20, 100, 20, 2];
  await page.request.post(new URL('/api/sku/rows', page.url()).href, { data: { rows: [
    { country: 'ES', brand: 'Series', model: '305', setGroup: 'BK', sku: 'SERIES-BK', asin: one },
    { country: 'ES', brand: 'Series', model: '305XL', setGroup: 'BKC', sku: 'SERIES-BKC', asin: two },
    { country: 'ES', brand: 'Series', model: '305', setGroup: 'BK', sku: 'SERIES-DUPLICATE-ASIN', asin: one },
  ] } });
  await attach([{ name: 'series_one.csv', text: asinFixture({ asin: one, rows: [oneRow] }) }, { name: 'series_two.csv', text: asinFixture({ asin: two, rows: [twoRow] }) }]);
  await view.getByRole('button', { name: '上传并保存' }).click();
  await view.getByText(/B000002001.*已保存 1 条/).waitFor();
  await idle();
  await view.getByLabel('词类型', { exact: true }).selectOption('all');
  await view.getByLabel('显示方式', { exact: true }).selectOption('queries');
  await idle();
  const modelOption = await view.getByLabel('墨盒型号', { exact: true }).locator('option').filter({ hasText: 'Series · 305' }).getAttribute('value');
  await view.getByLabel('墨盒型号', { exact: true }).selectOption(modelOption);
  await idle();
  assert.equal(await rows().count(), 1);
  assert.equal(await rows().first().locator('td').nth(2).innerText(), '1,000');
  assert.equal(await rows().first().locator('td').nth(7).innerText(), '30');
  assert.equal(await rows().first().locator('td').nth(8).innerText(), '7');
  assert.equal(await rows().first().locator('td').nth(10).innerText(), '35.00%');
  assert.match(await rows().first().innerText(), /合并 2 个 ASIN/);
  await view.getByLabel('显示方式', { exact: true }).selectOption('printers');
  await idle();
  await view.getByRole('button', { name: '展开 Series · 305 HP DESKJET2820', exact: true }).click();
  const seriesChildren = view.getByRole('region', { name: 'Series · 305 HP DESKJET2820 下的搜索词', exact: true });
  await seriesChildren.locator('.aba-table').waitFor();
  assert.equal(await seriesChildren.locator('tbody tr').count(), 1);
  assert.match(await seriesChildren.locator('.aba-group-context').innerText(), /ASIN 总点击 30.*ASIN 总购买 7/);
  await page.request.post(new URL('/api/aba/asin/import', page.url()).href, { data: { marketplace: 'ES', files: [{ name: 'series_two.csv', text: asinFixture({ asin: two, rows: [[...twoRow.slice(0, 4), 25, ...twoRow.slice(5)]] }) }] } });
  await view.getByLabel('显示方式', { exact: true }).selectOption('queries');
  await idle();
  assert.equal(await rows().first().locator('td').nth(4).innerText(), '—');
  assert.equal(await rows().first().locator('td').nth(5).innerText(), '—');
  assert.equal(await rows().first().locator('td').nth(10).innerText(), '—');
  await view.locator('.aba-market-conflict summary').click();
  assert.match(await view.locator('.aba-market-conflict').innerText(), /B000002001 = 20.*B000002002 = 25/);
  await view.locator('.aba-table-heading').scrollIntoViewIfNeeded();
  await page.screenshot({ path: output + 'aba-series-conflict.png', fullPage: true });
  assert.deepEqual(errors, []);
  console.log('ASIN browser passed: CSV/XLSX, filters, SKU linkage, printer groups, model/color-set merge, market deduplication/conflict review, pagination/retry and privacy.');
} finally {
  await browser?.close();
  await vite?.close();
  await backend.close();
}
